version: "3.9"

services:
  backend:
    build:
      context: ./BackEnd
    ports:
      - "5000:80"
    volumes:
        - sqlite_data:/app/data
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  frontend:
    build:
      context: ./FrontEnd
    ports:
      - "5173:80"

volumes:
  sqlite_data: