name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ./BackEnd/InventoryControl.API
    - name: Build
      run: dotnet build ./BackEnd/InventoryControl.API --no-restore
    - name: Test
      run: dotnet test ./BackEnd/InventoryControl.Test/InventoryControl.Test.csproj
